language: r
sudo: required
cache: packages
warnings_are_errors: false

r_binary_packages:
  - Rcpp
  - testthat

r_packages:
  - devtools

# Install development package
r_github_packages:
  - skgrange/threadr

